name: hadoop
services:
  namenode:
    image: apache/hadoop:3
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - "9870:9870"
    env_file: ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    volumes:
      - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro

  datanode:
    image: apache/hadoop:3
    command: ["hdfs", "datanode"]
    env_file: ./config
    volumes:
      - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro

  resourcemanager:
    image: apache/hadoop:3
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - "8088:8088"
    env_file: ./config
    volumes:
      - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - ./conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml:ro

  nodemanager:
    image: apache/hadoop:3
    command: ["yarn", "nodemanager"]
    env_file: ./config
    volumes:
      - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - ./conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml:ro

